### ISSUE TITLE
Backup function broken

### ISSUE THREAD

**Issue by crashfistfight** [TeamWin/android_device_sony_pioneer#1]
In latest twrp the backup function is broken.

Output: can not create '/data/media/0/TRWP' folder. (Operation not permitted)
If looking at /data/media/0/ with the integrated file-manager, only random text is shown as folders. 
(fastboot boot twrp-3.2.3-2-pioneer.img)

On build twrp-3.2.3-1 everything works as expected. 
(fastboot boot twrp-3.2.3-1-pioneer.img)

**Comment by Dees-Troy** [comment]
The random text file names are because your device has been encrypted with File Based Encryption. Sounds like this TWRP isn't set up to decrypt FBE on this device.

**Comment by luk1337** [comment]
Latest build is supposed to decrypt FBE on devices running Android 9, if you're on Android 8 then it (probably) won't decrypt it.

**Comment by crashfistfight** [comment]
I just followed the given instruction on https://wiki.lineageos.org/devices/pioneer/install for trwp and the recommended backup. This is happening indeed on latest oreo stock firmware.
